-- ============================================================
-- SOFT USER RESET SCRIPT
-- Preserves enriched_profiles and enriched_companies (shared pools)
-- Resets user_connections pipeline state so the pipeline re-runs
-- Run in Supabase SQL Editor
-- Change the email on the next line to the user you want to reset
-- ============================================================

DO $$
DECLARE
  target_email TEXT := 'saras@incommon.co';  -- CHANGE THIS
  target_user_id UUID;
  conn_count INT;
BEGIN
  -- Find the user ID
  SELECT id INTO target_user_id FROM public.users WHERE email = target_email;

  IF target_user_id IS NULL THEN
    SELECT id INTO target_user_id FROM auth.users WHERE email = target_email;
  END IF;

  IF target_user_id IS NULL THEN
    RAISE NOTICE 'No user found with email: %', target_email;
    RETURN;
  END IF;

  RAISE NOTICE 'Soft-resetting user: % (ID: %)', target_email, target_user_id;

  -- Count connections before reset
  SELECT COUNT(*) INTO conn_count FROM public.user_connections WHERE user_id = target_user_id;
  RAISE NOTICE 'Found % connections to reset', conn_count;

  -- Reset classification fields
  UPDATE public.user_connections
  SET
    classification_status = 'pending',
    seniority_tier = NULL,
    function_category = NULL,
    decision_maker_likelihood = NULL,
    connection_type_signal = NULL,
    enrichment_tier = NULL,
    enrichment_status = 'pending',
    enrichment_error = NULL,
    is_free_tier_selection = FALSE,
    match_score = NULL,
    match_type = NULL,
    match_reasons = NULL,
    suggested_approach = NULL,
    scored_at = NULL
  WHERE user_id = target_user_id;
  RAISE NOTICE 'Reset all user_connections pipeline fields';

  -- Reset user processing status
  UPDATE public.users
  SET
    processing_status = 'idle',
    processing_progress = 0
  WHERE id = target_user_id;
  RAISE NOTICE 'Reset user processing status to idle';

  -- Delete old matches (will be regenerated by scoring pipeline)
  DELETE FROM public.matches WHERE user_id = target_user_id;
  RAISE NOTICE 'Deleted old matches';

  -- Delete prompt_runs (optional, keeps logs clean)
  DELETE FROM public.prompt_runs WHERE user_id = target_user_id;
  RAISE NOTICE 'Deleted prompt_runs';

  RAISE NOTICE 'DONE — soft reset for %. enriched_profiles and enriched_companies preserved.', target_email;
  RAISE NOTICE 'The pipeline will re-run on next dashboard visit: classify -> enrich -> score -> complete';
END $$;
